version: '3.9'

services:
  db:
    image: 'postgres'
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'mydb'
  server:
    build: .
    ports:
      - '3000:3000'
