"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var loginMiddleware_1 = require("../../middleware/loginMiddleware");
var gameModeControllers_1 = require("../../controllers/gameModeControllers/gameModeControllers");
var gamemodeMiddleware_1 = require("../../middleware/gamemodeMiddleware");
var router = express_1.default.Router();
router.get('/', gameModeControllers_1.getGameModeController);
router.post('/', loginMiddleware_1.ensureAuthenticated, gameModeControllers_1.createGameModeController);
router.put('/', loginMiddleware_1.ensureAuthenticated, gamemodeMiddleware_1.isGameModeOwner, gameModeControllers_1.updateGameModeController);
router.delete('/', loginMiddleware_1.ensureAuthenticated, gamemodeMiddleware_1.isGameModeOwner, gameModeControllers_1.deleteGameModeController);
router.get('/images', gameModeControllers_1.getAllImagesController);
exports.default = router;
