"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var imagesController_1 = require("../../controllers/imagesControllers/imagesController");
var loginMiddleware_1 = require("../../middleware/loginMiddleware");
var imageMiddleware_1 = require("../../middleware/imageMiddleware");
var router = express_1.default.Router();
router.get('/', imagesController_1.getImageController);
router.post('/', loginMiddleware_1.ensureAuthenticated, imagesController_1.createImageController);
router.put('/', loginMiddleware_1.ensureAuthenticated, imageMiddleware_1.isImageOwner, imagesController_1.updateImageController);
router.delete('/', loginMiddleware_1.ensureAuthenticated, imageMiddleware_1.isImageOwner, imagesController_1.deleteImageController);
exports.default = router;
