apiVersion: apps/v1
kind: Deployment
metadata:
    name: serrata-api-express
    namespace: serrata
    labels:
        app: serrata-api-express
spec:
    replicas: 1
    selector:
        matchLabels:
            app: serrata-api-express
    template:
        metadata:
            labels:
                app: serrata-api-express
        spec:
            containers:
                - name: serrata-api-express
                  image: tang0ch4rlie/expressserrata:IMAGE_LABEL
                  ports:
                      - containerPort: 3000

                  env:
                      -   name: DATABASE_URL
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-express-secret
                                  key: DATABASE_URL
                      -   name: SECRET_KEY
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-express-secret
                                  key: SECRET_KEY
                      -   name: SEL
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-express-secret
                                  key: SEL
                      -   name: PERSONNAL_TOKEN
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-express-secret
                                  key: PERSONNAL_TOKEN
                      -   name: AWS_ACCESS_KEY
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-express-secret
                                  key: AWS_ACCESS_KEY
                      -   name: AWS_SECRET_ACCESS_KEY
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-express-secret
                                  key: AWS_SECRET_ACCESS_KEY
                      -   name: REGION
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-express-secret
                                  key: REGION
                      -   name: BUCKET_NAME
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-express-secret
                                  key: BUCKET_NAME
                  imagePullPolicy: Always
                  resources:
                      requests:
                          cpu: '250m'