apiVersion: v1
kind: Service
metadata:
  name: postgres-express
  namespace: serrata
  labels:
    app: postgres-express
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-express
    task: postgres-express
