name: node_express_app

on: 
    workflow_run:
        workflows: ["test-api"]
        types:
            - completed
jobs:
    build_and_push:
        name: Build Docker image
        runs-on: ubuntu-latest 
        steps:
            -   name: Checkout
                uses: actions/checkout@v3  

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   id: commit
                uses: prompt/actions-commit-hash@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}
                          
            -   name: Build and push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: true
                    tags: tang0ch4rlie/expressserrata:${{ steps.commit.outputs.short }}
    deploy:
        name: Deploy to Kubernetes Cluster
        needs: build_and_push
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v2
            -   id: commit
                uses: prompt/actions-commit-hash@v3
            -   name: Set Kubernetes Context
                uses: azure/k8s-set-context@v1
                with:
                    method: kubeconfig
                    kubeconfig: ${{ secrets.KUBE_CONFIG }}
            -   name: Replace Image Label
                run: sed -i'' -e 's/IMAGE_LABEL/${{ steps.commit.outputs.short }}/g' ".github/k8s/deployment.yml"
            -   name: Deploy to Cluster
                run: kubectl apply -f ".github/k8s/deployment.yml"