name: node_express_app

on: # specify the build to trigger the automated ci/cd
    push:
        branches:
            - "main"
jobs:
    build:
        name: Build Docker image
        runs-on: ubuntu-latest # specify the build machine
        steps:
            - # checkout to the repository on the build machine
                name: Checkout
                uses: actions/checkout@v3
            - # login to Docker Hub using the secrets provided
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}
            - # create a build kit builder instance
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Build and push Docker container
                run: |
                  docker buildx create --use
                  docker buildx build \
                    --file Dockerfile \
                    --tag tang0ch4rlie/expressserrata:latest \
                    --platform linux/amd64,linux/arm64,darwin/amd64 \
                    --push .
