name: test-api

on:
    push:
        branches:
            - "main"

jobs:
    build:
        name: Build and install nodejs
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3  
            -   name: Setup node
                uses: actions/setup-node@v1
                with:
                    node-version: 18.x   
            -   run: npm ci
    
    # postgres:
    #     name: Install and setup postgres
    #     runs-on: ubuntu-latest
    #     steps:
    #         -   name: Install postresql
    #             run: |
    #                 sudo apt update
    #                 sudo apt install -y postgresql postgresql-contrib
    #                 sudo systemctl start postgresql.service
    #                 sudo -u postgres psql -f setup.sql

    test:
        name: Units test
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3 

            -   name: Test
                run: npm run dev